epic/urls.py
#
#   Copyright (c) 2014-2016, 2018 eGauge Systems LLC
# 	1644 Conestoga St, Suite 2
# 	Boulder, CO 80301
# 	voice: 720-545-9767
# 	email: davidm@egauge.net
#
#   All rights reserved.
#
#   This code is the property of eGauge Systems LLC and may not be
#   copied, modified, or disclosed without any prior and written
#   permission from eGauge Systems LLC.
#
from django.conf.urls import url

from epic import exports
from epic import views

urlpatterns = [
    url(r'^$', views.epic_index, name='epic_index'),
    url(r'^search-results$', views.search_results, name='search_results'),

    url(r'^part/?$', views.part_list, name='part_list'),
    url(r'^part/add$', views.part_add, name='part_add'),
    url(r'^part/info$', views.part_info, name='part_info'),
    url(r'^part/(?P<pk>\d+)/?$', views.part_detail, name='part_detail'),
    url(r'^part/(?P<pk>\d+)/edit$', views.part_edit, name='part_edit'),
    url(r'^part/(?P<pk>\d+)/delete$', views.part_delete, name='part_delete'),
    url(r'^part/(?P<pk>\d+)/bom/?$', views.part_bom_detail,
        name='part_bom_detail'),
    url(r'^part/(?P<pk>\d+)/bom/edit$', views.part_bom_edit,
        name='part_bom_edit'),
    url(r'^part/(?P<pk>\d+)/bom/export$', exports.part_bom_export,
        name='part_bom_export'),
    url(r'^part/(?P<pk>\d+)/bom/compare/?$',
        views.part_bom_compare, name='part_bom_compare'),
    url(r'^part/(?P<pk>\d+)/bom/compare/(?P<other_pk>\d+)/?$',
        views.part_bom_compare_qty, name='part_bom_compare_qty'),
    url(r'^part/(?P<pk>\d+)/bom/compare/(?P<other_pk>\d+)/refdes$',
        views.part_bom_compare_refdes, name='part_bom_compare_refdes'),
    url(r'^part/datasheet/?$', views.datasheet_list, name='datasheet_list'),
    url(r'^part/datasheet/add$', views.datasheet_add,
        name='datasheet_add'),
    url(r'^part/datasheet/add/(?P<pk>\d+)$', views.datasheet_add_part,
        name='datasheet_add_part'),
    url(r'^part/datasheet/(?P<pk>\d+)/?$', views.datasheet_detail,
        name='datasheet_detail'),
    url(r'^part/datasheet/(?P<pk>\d+)/edit$',
        views.datasheet_edit, name='datasheet_edit'),
    url(r'^part/datasheet/(?P<pk>\d+)/delete$', views.datasheet_delete,
        name='datasheet_delete'),

    url(r'^vendor/?$', views.vendor_list, name='vendor_list'),
    url(r'^vendor/add$', views.vendor_add, name='vendor_add'),
    url(r'^vendor/(?P<pk>\d+)/?$', views.vendor_detail, name='vendor_detail'),
    url(r'^vendor/(?P<pk>\d+)/edit$', views.vendor_edit, name='vendor_edit'),
    url(r'^vendor/(?P<pk>\d+)/delete$', views.vendor_delete,
        name='vendor_delete'),

    url(r'^warehouse/?$', views.warehouse_list, name='warehouse_list'),
    url(r'^warehouse/stock$', views.warehouse_stock_all,
        name='warehouse_stock_all'),
    url(r'^warehouse/stock/export$', exports.warehouse_stock_all_export,
        name='warehouse_stock_all_export'),
    url(r'^warehouse/add$', views.warehouse_add, name='warehouse_add'),
    url(r'^warehouse/(?P<pk>\d+)/?$', views.warehouse_detail,
        name='warehouse_detail'),
    # this is simply an alias since the warehouse_detail already lists
    # the inventories associated with that warehouse:
    url(r'^warehouse/(?P<pk>\d+)/inventory/?$',
        views.warehouse_inventory, name='warehouse_inventory'),
    url(r'^warehouse/(?P<pk>\d+)/edit$', views.warehouse_edit,
        name='warehouse_edit'),
    url(r'^warehouse/(?P<pk>\d+)/add-shipment$', views.warehouse_add_shipment,
        name='warehouse_add_shipment'),
    url(r'^warehouse/(?P<pk>\d+)/add-inventory$',
        views.warehouse_add_inventory, name='warehouse_add_inventory'),
    url(r'^warehouse/(?P<pk>\d+)/stock$', views.warehouse_stock,
        name='warehouse_stock'),
    url(r'^warehouse/(?P<pk>\d+)/stock/export$', exports.warehouse_stock_export,
        name='warehouse_stock_export'),
    url(r'^warehouse/(?P<pk>\d+)/delete$', views.warehouse_delete,
        name='warehouse_delete'),
    url(r'^warehouse/(?P<warehouse>\d+)/inventory/(?P<pk>\d+)$',
        views.warehouse_inv_detail, name='warehouse_inventory_detail'),
    url(r'^warehouse/(?P<warehouse>\d+)/inventory/(?P<pk>\d+)/export$',
        exports.warehouse_inv_export, name='warehouse_inventory_export'),
    url(r'^warehouse/(?P<warehouse>\d+)/inventory/(?P<pk>\d+)/edit$',
        views.inventory_edit, name='warehouse_inventory_edit'),
    url(r'^warehouse/(?P<warehouse>\d+)/inventory/(?P<pk>\d+)/delete$',
        views.inventory_delete, name='warehouse_inventory_delete'),

    url(r'^order/?$', views.order_list, name='order_list'),
    url(r'^order/add$', views.order_add, name='order_add'),
    url(r'^order/(?P<pk>\d+)/?$', views.order_detail, name='order_detail'),
    url(r'^order/(?P<pk>\d+)/export$', exports.order_export,
        name='order_export'),
    url(r'^order/(?P<pk>\d+)/edit$', views.order_edit, name='order_edit'),
    url(r'^order/(?P<pk>\d+)/check-stock$', views.order_check_stock,
        name='order_check_stock'),
    url(r'^order/(?P<pk>\d+)/add-shipment$', views.order_add_shipment,
        name='order_add_shipment'),
    url(r'^order/(?P<pk>\d+)/delete$', views.order_delete, name='order_delete'),

    url(r'^ship/?$', views.ship_list, name='ship_list'),
    url(r'^ship/add$', views.ship_add, name='ship_add'),
    url(r'^ship/(?P<pk>\d+)/?$', views.ship_detail, name='ship_detail'),
    url(r'^ship/(?P<pk>\d+)/export$', exports.ship_export, name='ship_export'),
    url(r'^ship/(?P<pk>\d+)/edit$', views.ship_edit, name='ship_edit'),
    url(r'^ship/(?P<pk>\d+)/delete$', views.ship_delete, name='ship_delete'),

    url(r'^dal/part/?$', views.Part_Autocomplete.as_view(), name='part-dal'),
    url(r'^dal/assy/?$', views.Assembly_Autocomplete.as_view(),
        name='assembly-dal'),
    url(r'^dal/order/?$', views.Order_Autocomplete.as_view(), name='order-dal'),
    url(r'^dal/mfg/?$', views.Mfg_Autocomplete.as_view(), name='mfg-dal'),
    url(r'^dal/footprint/?$', views.Footprint_Autocomplete.as_view(),
        name='footprint-dal'),]

epic/models.py
#
#   Copyright (c) 2014-2018 eGauge Systems LLC
# 	1644 Conestoga St, Suite 2
# 	Boulder, CO 80301
# 	voice: 720-545-9767
# 	email: davidm@egauge.net
#
#   All rights reserved.
#
#   This code is the property of eGauge Systems LLC and may not be
#   copied, modified, or disclosed without any prior and written
#   permission from eGauge Systems LLC.
#
# pylint: disable=too-few-public-methods, no-member
from __future__ import print_function

import hashlib
import math
import re

from datetime import date, timedelta
from decimal import Decimal
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from django.utils.html import escape
from django.contrib.humanize.templatetags.humanize import intcomma

from epic.compat import reverse

PART_PRICE_VALIDATORS = [MinValueValidator(Decimal('0.000001'))]

def strchoice(choices, val):
    for key, name in choices:
        if key == val:
            return name
    return val

def part_cost(line_cost, qty):
    if qty <= 0:
        return 0
    return Decimal('%.6f' % (float(line_cost) / qty))

def format_part_number(part):
    return 'EP%05u' % part

def html_part_link(part):
    """Return an HTML link for PART.  PART may be either a Part object or
    a part number.
    """
    if isinstance(part, Part):
        pn = part.id
    else:
        pn = part
    name = format_part_number(pn)
    url = reverse('epic:part_detail', kwargs={'pk': pn})
    return '<a href="%s">%s</a>' % (url, name)

def html_list_or_none(l):
    """If L is empty, return 'none', otherwise, join the list using ','
    as a separator.
    """
    html = ', '.join(l)
    if html != '':
        return html
    return '<em>&mdash;None&mdash;</em>'

class Datasheet(models.Model):
    name = models.CharField(max_length=128, unique=True, blank=False)
    ds_file = models.FileField(
        upload_to=getattr(settings, 'EPIC_DATASHEET_DIR', 'epic/datasheets'),
        blank=False,
        verbose_name='Datasheet File')
    notes = models.CharField(
        max_length=1024, help_text='For misc. information that may be useful '
        'along with the datasheet, such as website retrieved from.',
        blank=True)
    md5sum = models.CharField(max_length=36, null=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return '%s' % self.name

    def html_link(self):
        url = reverse('epic:datasheet_detail', kwargs={'pk': self.id})
        return '<a href="%s">%s</a>' % (url, self.name)

    def save(self, *args, **kwargs):
        md5 = hashlib.md5()
        for chunk in self.ds_file.chunks():
            md5.update(chunk)
        self.md5sum = md5.hexdigest()
        super(Datasheet, self).save(*args, **kwargs)

    # See signals.datasheet_delete() for deletion cleanup.

class Part(models.Model):
    MOUNTING_SMD = 0
    MOUNTING_THD = 1
    MOUNTING_CHASSIS = 2
    MOUNTING_FREE = 3
    MOUNTING_CHOICES = (
        (MOUNTING_SMD, 'SMD'),
        (MOUNTING_THD, 'THD'),
        (MOUNTING_CHASSIS, 'chassis'),
        (MOUNTING_FREE, 'free')
    )
    STATUS_PREVIEW = 0
    STATUS_ACTIVE = 1
    STATUS_PREFERRED = 2
    STATUS_DEPRECATED = 3
    STATUS_OBSOLETE = 4
    STATUS_CHOICES = (
        (STATUS_PREVIEW, 'preview'),
        (STATUS_ACTIVE, 'active'),
        (STATUS_PREFERRED, 'preferred'),
        (STATUS_DEPRECATED, 'deprecated'),
        (STATUS_OBSOLETE, 'obsolete'),
    )
    # deprecated parts are orderable, but preview or obsolete parts
    # are not:
    STATUS_ORDERABLE = (STATUS_ACTIVE, STATUS_PREFERRED, STATUS_DEPRECATED)
    # what modified the part's BOM (assembly-items list) last (user or tool)?:
    LAST_MOD_TYPE_USER	= 0
    LAST_MOD_TYPE_TOOL	= 1
    LAST_MOD_CHOICES = (
        (LAST_MOD_TYPE_USER, 'user'),
        (LAST_MOD_TYPE_TOOL, 'tool')
    )

    val = models.CharField(max_length=31, verbose_name='Value', blank=True,
                           default='',
                           help_text='The primary value of the part '
                           'such as resistance for a resistor or '
                           'capacitance for a capacitor.')
    descr = models.CharField(max_length=127, verbose_name='Description',
                             blank=True, default='',
                             help_text='Brief listing of key parameters of '
                             'the part, such as temperature range, drift, '
                             'max. voltages, etc.')
    footprint = models.CharField(max_length=63, blank=True, default='',
                                 help_text='The part\'s PCB footprint.')
    mfg = models.CharField(max_length=31, verbose_name='Manufacturer',
                           help_text='The name of the manufacturer of the '
                           'part.')
    mfg_pn = models.CharField(max_length=31,
                              verbose_name='Manufacturer\'s Part #')
    mounting = models.IntegerField(choices=MOUNTING_CHOICES,
                                   default=MOUNTING_SMD, blank=False,
                                   verbose_name='Mounting Type',
                                   help_text='How the part is mounted to a '
                                   'PCB (free if it\'s not mounted at all, '
                                   'such as a plug).')
    target_price = models.DecimalField(max_digits=10, decimal_places=6,
                                       validators=PART_PRICE_VALIDATORS,
                                       verbose_name='Target price [$]',
                                       help_text='The expected price of the '
                                       'part.')
    overage = models.DecimalField(max_digits=6, decimal_places=3,
                                  validators=[
                                      MinValueValidator(Decimal('0')),
                                      MaxValueValidator(Decimal('100'))],
                                  verbose_name='Overage [%]',
                                  help_text='Worst-case percentage of parts '
                                  'we expect to lose due to attrition at the '
                                  'assembly-house.')
    spq = models.IntegerField(default=1,
                              verbose_name='Standard-Package Qty',
                              help_text='The number of parts in '
                              'a standard package.  For example, 10,000 '
                              'pieces in a reel.')
    lead_time = models.PositiveIntegerField(verbose_name='Lead-time [weeks]',
                                            help_text='Lead-time in weeks.')
    status = models.IntegerField(choices=STATUS_CHOICES,
                                 default=STATUS_PREVIEW, blank=False,
                                 verbose_name='Life-time Status',
                                 help_text='The life-time status of this '
                                 'part. Parts marked `preview\' and '
                                 '`obsolete\' are not considered orderable.')
    substitute = models.ForeignKey('self', null=True, blank=True,
                                   verbose_name='Substitutes',
                                   help_text='List of other parts that are '
                                   '(identical) substitutes for this part.',
                                   on_delete=models.CASCADE)
    last_bom_mod_type = models.IntegerField(choices=LAST_MOD_CHOICES,
                                            default=LAST_MOD_TYPE_USER,
                                            blank=False)
    last_bom_mod_name = models.CharField(max_length=31, blank=True, default='',
                                         help_text='Name of entity '
                                         'which last modified this part.')
    datasheet = models.ForeignKey(Datasheet, null=True, blank=True,
                                  on_delete=models.CASCADE)
    notes = models.TextField(blank=True, default='', help_text='Notes '
                             'regarding this part.')

    equiv_parts = None
    best_parts = {}

    class Meta:
        ordering = ['id']
        unique_together = ('mfg', 'mfg_pn')
        index_together = [
            ['mfg', 'mfg_pn']
        ]

    def __str__(self):
        return '%s' % (format_part_number(self.id))

    @classmethod
    def flush_caches(cls, sender, **kwargs):
        # pylint: disable=unused-argument
        """See signals.flush_caches()."""
        # clear the caches when a part changes:
        Part.equiv_parts = None
        Part.best_parts = {}

    def equivalent_parts(self):
        """Return the set of equivalent parts for this part.  The set includes
        the part itself.  However, if the part doesn't have an id yet
        (newly created and not saved yet), the empty set is returned.

        """

        def get_set(part):
            if part.id not in Part.equiv_parts:
                Part.equiv_parts[part.id] = frozenset([part])
            return Part.equiv_parts[part.id]

        if self.id is None:
            # newly created parts don't have a valid id yet so they can't
            # be hashed, which also means nobody can be referring to it,
            # which means its equivalent-parts-set is empty.
            return frozenset([])

        if Part.equiv_parts is None:
            Part.equiv_parts = {}
            for p in Part.objects.exclude(substitute__isnull=True):
                union = get_set(p)
                union |= get_set(p.substitute)
                for q in union:
                    Part.equiv_parts[q.id] = union
        return get_set(self)

    def best_part(self):
        """Among the set of parts equivalent to this part, find orderable,
        preferred or lowest-cost part.  Returns part itself if nothing
        better is available.

        """
        if self.id in Part.best_parts:

epic/templates/epic/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
	{{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group">
    {% endif %}
	<{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" class="form-group{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-error{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
		{% if field.label and not field|is_checkbox and form_show_labels %}
			<label for="{{ field.id_for_label }}" class="control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
				{{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
			</label>
		{% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap3/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap3/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                {% if label_class %}
                    <div class="controls col-lg-offset-{{ label_size }} {{ field_class }}">
                {% endif %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field 'class' 'checkbox' %}
                    {{ field.label|safe }}
                    {% include 'bootstrap3/layout/help_text_and_errors.html' %}
                </label>
                {% if label_class %}
                    </div>
                {% endif %}
            {% else %}
                <div class="controls {{ field_class }}">
                    {% crispy_field field %}
                    {% include 'bootstrap3/layout/help_text_and_errors.html' %}
                </div>
            {% endif %}
        {% endif %}
	</{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        </div>
    {% endif %}
{% endif %}

epic/templates/epic/inline_formset.html
{% load crispy_forms_tags %}
{% load crispy_forms_utils %}
{% load crispy_forms_field %}

{% specialspaceless %}
{% if formset_tag %}
<form {{ flat_attrs|safe }} method="{{ form_method }}" {% if formset.is_multipart %} enctype="multipart/form-data"{% endif %}>
{% endif %}
    {% if formset_method|lower == 'post' and not disable_csrf %}
        {% csrf_token %}
    {% endif %}

    <div>
        {{ formset.management_form|crispy }}
    </div>

    <table{% if form_id %} id="{{ form_id }}_table"{% endif%} class="table table-striped table-condensed">
        <thead>
          {% if formset.readonly and not formset.queryset.exists %}
          {% else %}
              <tr>
                  {% for field in formset.forms.0 %}
                      {% if field.label and not field.is_hidden %}
                          <th for="{{ field.auto_id }}" class="control-label {% if field.field.required %}requiredField{% endif %}">
                              {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
                          </th>
                      {% endif %}
                  {% endfor %}
              </tr>
          {% endif %}
        </thead>

        <tbody>
            {% for form in formset %}
                {% if form_show_errors and not form.is_extra %}
                    {% include "bootstrap3/errors.html" %}
                {% endif %}

                <tr>
                    {% for field in form %}
                        {% include 'epic/field.html' with tag="th" form_show_labels=False %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if inputs %}
        <div class="form-actions">
            {% for input in inputs %}
                {% include "uni_form/layout/baseinput.html" %}
            {% endfor %}
        </div>
    {% endif %}
{% if formset_tag %}</form>{% endif %}
{% endspecialspaceless %}

epic/templates/epic/inventory_edit.html
{% extends "epic/base_layout.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block extrahead %}
{{ block.super }}
{{ inv_form.media }}	<!-- for django-bootstrap3-datetimepicker -->
{{ item_form.media }}
<script src="{% static "epic/js/editing.js" %}"></script>
{% endblock extrahead %}

{% block content %}
{{ block.super }}

<form method="POST" enctype="multipart/form-data">

<div class="form-horizontal">
  {% crispy inv_form %}
</div>

{% crispy item_form %}

<div class="form-actions">
  <input type="submit" name="save" value="Save" class="btn btn-primary">
  <input type="submit" name="save-and-zero" value="Save & Zero-out"
	  class="btn btn-secondary"
	  title="Save this inventory and create zero-quantity entries for parts not already listed.">
  <input type="submit" name="save-and-done" value="Save & Done"
	 class="btn btn-default">
  <input type="submit" name="cancel" value="Cancel"
	 class="btn btn-default">
</div>
</form>

<br>

{% endblock content %}

epic/templates/epic/order_list.html
{% extends "epic/base_layout.html" %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block buttons %}
  <a class="btn btn-default" href="{% url 'epic:epic_index' %}">
    Up <i class="glyphicon glyphicon-chevron-up"></i>
  </a>

  <a class="btn btn-primary" href="{% url 'epic:order_add' %}">
    Add New Order <i class="glyphicon glyphicon-plus"></i></a>
{% endblock buttons %}

{% block content %}
{{ block.super }}

<div class="panel panel-default">
  <div class="panel-heading">
    <form class="form-horizontal" role="form" method="GET" id="filter_by">
      <div class="form-group">
	<div class="col-md-6">
	  <select class="form-control" name="st"
		  onchange="javascript:$('#filter_by').submit();">
	    <option value='all' {% if st == "all" %}selected{% endif %}>
	      View All Orders</option>
	    <option value='open' {% if st == "open" %}selected{% endif %}>
	      View Open Orders</option>
	    <option value='closed' {% if st == "closed" %}selected{% endif %}>
	      View Closed Orders</option>
	  </select>
	</div>
      </div>
    </form>
  </div>

  <div class="panel-body">
    <table class="table-responsive table-condensed bootstrap-extended-table"
            style="background-color: white"
            data-toggle="table"
            data-striped="true"
            data-search="true"
            data-sortable="true"
            data-pagination="true"
            data-side-pagination="client"
            data-page-number="1"
            data-page-size="50"
            data-pagination-first-text="First"
            data-pagination-pre-text="Previous"
            data-pagination-next-text="Next"
            data-pagination-last-text="Last"
            data-show-pagination-switch="true"
            data-pagination-v-align="top"
            data-pagination-h-align="right">
      <thead>
	<tr>
	  <th data-sortable="true">PO#</th>
	  <th data-sortable="true">Order Date</th>
	  <th data-sortable="true">Exp. Arrival</th>
	  <th data-sortable="true">Status</th>
	  <th data-sortable="true">Vendor</th>
	  <th data-sortable="true">Ship-To</th>
	  <th>Cost</th>
	  <th data-sortable="true">Notes</th>
	</tr>
      </thead>
      {% for order in order_list %}
      <tr
	 {% with order.days_until_past_due as days_to_live %}
         {%   if order.is_open %}
         {%     if days_to_live <= 0 %}class="danger"
	 {%     elif days_to_live > 0 and days_to_live < 7 %}class="warning"
	 {%     elif days_to_live >= 7 %}class="success"
         {%     endif %}
         {%   endif %}
	 {% endwith %}>
	<td>{{ order.html_link|safe }}</td>
	<td>{{ order.ts|date:"Y‑m‑d" }}</td>
	<td>{{ order.expected_arrival_date|date:"Y‑m‑d" }}</td>
	<td>{{ order.get_status_display }}</td>
	<td>{{ order.vendor.html_link|safe }}</td>
	<td>{{ order.warehouse.html_link|safe }}</td>
	<td class='text-right'>
	  $&nbsp;{{ order.total_cost|floatformat:2|intcomma }}
	</td>
	<td>{{ order.notes|linebreaksbr }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

{% endblock content %}

epic/templates/epic/part_edit.html
{% extends "epic/base_layout.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block extrahead %}
{{ block.super }}
{{ part_form.media }}
{{ vendor_form.media }}
<script src="{% static "epic/js/editing.js" %}"></script>
<script src="{% static "epic/js/substitute-editor.js" %}"></script>
{% endblock extrahead %}

{% block content %}
{{ block.super }}

<form method="POST">
<div class="form-horizontal">
{% crispy part_form %}
</div>
{% crispy vendor_form %}

<div class="form-actions">
  <input type="submit" name="save" value="Save" class="btn btn-primary">
  <input type="submit" name="cancel" value="Cancel"
	 class="btn btn-default">
</div>
</form>

<br>

{% endblock content %}

epic/templates/epic/search_results.html
{% extends "epic/base_layout.html" %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block buttons %}
  <a class="btn btn-default" href="{% url 'epic:epic_index' %}">
    Up <i class="glyphicon glyphicon-chevron-up"></i>
  </a>
{% endblock buttons %}

{% block content %}
{{ block.super }}

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Parts matching search
      for &ldquo;{{ q }}&rdquo;</h3>
  </div>
  <div class="panel-body">
    {{ parts_pager|safe }}
    <ul>
      {% for part in parts %}
      <li>{{ part.html_link|safe }}:
	{% if part.val %}
	{{ part.val }}
	{% else %}
	{{ part.descr }}
	{% endif %}
	({{ part.mfg }} {{ part.mfg_pn }},
	<span
	   class="epic_{% if part.is_orderable %}ok{% else %}alert{% endif %}">
	  {{ part.strstatus }})
	</span>
      </li>
      {% empty %}
      <em>&mdash; None &mdash;</em>
      {% endfor %}
    </ul>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Transactions matching search
      for &ldquo;{{ q }}&rdquo;</h3>
  </div>
  <div class="panel-body">
    {{ txtns_pager|safe }}
    <ul>
	{% for txtn in txtns %}
	<li>{{ txtn.html_link|safe }}: {{ txtn.description|safe }}</li>
	{% empty %}
	<em>&mdash; None &mdash;</em>
	{% endfor %}
    </ul>
  </div>
</div>

<br>

{% endblock content %}

epic/templates/epic/shipment_edit.html
{% extends "epic/base_layout.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block extrahead %}
{{ block.super }}
{{ ship_form.media }}	<!-- for django-bootstrap3-datetimepicker -->
{{ item_form.media }}
<script src="{% static "epic/js/editing.js" %}"></script>
{% endblock extrahead %}

{% block content %}
{{ block.super }}

<form method="POST" enctype="multipart/form-data">

<div class="form-horizontal">
  {% crispy ship_form %}
</div>

{% crispy item_form %}

<div class="form-actions">
  <input type="submit" name="save" value="Save" class="btn btn-primary">
  <input type="submit" name="save-and-done" value="Save & Done"
	 class="btn btn-default">
  <input type="submit" name="cancel" value="Cancel"
	 class="btn btn-default">
</div>
</form>

<br>

{% endblock content %}